### ISSUE TITLE
Delete Inscription disabled

### ISSUE THREAD

**Issue by zpalmtree** [LibrePlex/libreplex-program-library#69]
Hi, was checking the code and I see Delete Inscription is currently commented out:

https://github.com/LibrePlex/libreplex-program-library/blob/main/programs/libreplex_inscriptions/src/lib.rs#L53

May I ask why? I am interested in using this instruction

Thanks

**Comment by nilpferdschaefer** [comment]
Hi there! 

That instruction used to exist in a very old version of the repo but there are no plans to allow inscriptions to be deleted.

You can resize an instruction and reclaim the rent but you cannot close / delete the inscription itself.

Inscription order numbers are eternal and permanently associated with their corresponding root (usually the mint).

**Comment by zpalmtree** [comment]
Okay, thanks
